// Code generated by MockGen. DO NOT EDIT.
// Source: internal/powerflex/powerflex.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	goscaleio "github.com/dell/goscaleio"
	goscaleio0 "github.com/dell/goscaleio/types/v1"
	gomock "github.com/golang/mock/gomock"
	powerflex "github.com/rgolangh/xcopy-volume-populator/internal/powerflex"
)

// MockPowerFlexClient is a mock of PowerFlexClient interface.
type MockPowerFlexClient struct {
	ctrl     *gomock.Controller
	recorder *MockPowerFlexClientMockRecorder
}

// MockPowerFlexClientMockRecorder is the mock recorder for MockPowerFlexClient.
type MockPowerFlexClientMockRecorder struct {
	mock *MockPowerFlexClient
}

// NewMockPowerFlexClient creates a new mock instance.
func NewMockPowerFlexClient(ctrl *gomock.Controller) *MockPowerFlexClient {
	mock := &MockPowerFlexClient{ctrl: ctrl}
	mock.recorder = &MockPowerFlexClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPowerFlexClient) EXPECT() *MockPowerFlexClientMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockPowerFlexClient) Authenticate(goscaleioconfigConnect *goscaleio.ConfigConnect) (goscaleio.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", goscaleioconfigConnect)
	ret0, _ := ret[0].(goscaleio.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockPowerFlexClientMockRecorder) Authenticate(goscaleioconfigConnect interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockPowerFlexClient)(nil).Authenticate), goscaleioconfigConnect)
}

// FindSystem mocks base method.
func (m *MockPowerFlexClient) FindSystem(instanceID, name, href string) (*goscaleio.System, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSystem", instanceID, name, href)
	ret0, _ := ret[0].(*goscaleio.System)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSystem indicates an expected call of FindSystem.
func (mr *MockPowerFlexClientMockRecorder) FindSystem(instanceID, name, href interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSystem", reflect.TypeOf((*MockPowerFlexClient)(nil).FindSystem), instanceID, name, href)
}

// GetVolume mocks base method.
func (m *MockPowerFlexClient) GetVolume(param1, volumeID, param3, param4 string, flag bool) ([]*goscaleio0.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVolume", param1, volumeID, param3, param4, flag)
	ret0, _ := ret[0].([]*goscaleio0.Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVolume indicates an expected call of GetVolume.
func (mr *MockPowerFlexClientMockRecorder) GetVolume(param1, volumeID, param3, param4, flag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVolume", reflect.TypeOf((*MockPowerFlexClient)(nil).GetVolume), param1, volumeID, param3, param4, flag)
}

// NewVolume mocks base method.
func (m *MockPowerFlexClient) NewVolume() (powerflex.VolumeWrapper, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewVolume")
	ret0, _ := ret[0].(powerflex.VolumeWrapper)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewVolume indicates an expected call of NewVolume.
func (mr *MockPowerFlexClientMockRecorder) NewVolume() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewVolume", reflect.TypeOf((*MockPowerFlexClient)(nil).NewVolume))
}

// MockPowerFlexVolume is a mock of PowerFlexVolume interface.
type MockPowerFlexVolume struct {
	ctrl     *gomock.Controller
	recorder *MockPowerFlexVolumeMockRecorder
}

// MockPowerFlexVolumeMockRecorder is the mock recorder for MockPowerFlexVolume.
type MockPowerFlexVolumeMockRecorder struct {
	mock *MockPowerFlexVolume
}

// NewMockPowerFlexVolume creates a new mock instance.
func NewMockPowerFlexVolume(ctrl *gomock.Controller) *MockPowerFlexVolume {
	mock := &MockPowerFlexVolume{ctrl: ctrl}
	mock.recorder = &MockPowerFlexVolumeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPowerFlexVolume) EXPECT() *MockPowerFlexVolumeMockRecorder {
	return m.recorder
}

// MapVolumeSdc mocks base method.
func (m *MockPowerFlexVolume) MapVolumeSdc(mapVolumeSdcParam *goscaleio0.MapVolumeSdcParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MapVolumeSdc", mapVolumeSdcParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// MapVolumeSdc indicates an expected call of MapVolumeSdc.
func (mr *MockPowerFlexVolumeMockRecorder) MapVolumeSdc(mapVolumeSdcParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapVolumeSdc", reflect.TypeOf((*MockPowerFlexVolume)(nil).MapVolumeSdc), mapVolumeSdcParam)
}

// UnmapVolumeSdc mocks base method.
func (m *MockPowerFlexVolume) UnmapVolumeSdc(unmapVolumeSdcParam *goscaleio0.UnmapVolumeSdcParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmapVolumeSdc", unmapVolumeSdcParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmapVolumeSdc indicates an expected call of UnmapVolumeSdc.
func (mr *MockPowerFlexVolumeMockRecorder) UnmapVolumeSdc(unmapVolumeSdcParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmapVolumeSdc", reflect.TypeOf((*MockPowerFlexVolume)(nil).UnmapVolumeSdc), unmapVolumeSdcParam)
}

// MockPowerFlexSystem is a mock of PowerFlexSystem interface.
type MockPowerFlexSystem struct {
	ctrl     *gomock.Controller
	recorder *MockPowerFlexSystemMockRecorder
}

// MockPowerFlexSystemMockRecorder is the mock recorder for MockPowerFlexSystem.
type MockPowerFlexSystemMockRecorder struct {
	mock *MockPowerFlexSystem
}

// NewMockPowerFlexSystem creates a new mock instance.
func NewMockPowerFlexSystem(ctrl *gomock.Controller) *MockPowerFlexSystem {
	mock := &MockPowerFlexSystem{ctrl: ctrl}
	mock.recorder = &MockPowerFlexSystemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPowerFlexSystem) EXPECT() *MockPowerFlexSystemMockRecorder {
	return m.recorder
}
